// 
// Copyright (C) Microsoft. All rights reserved.
//

// THIS IS ONLY HERE FOR UNIT TESTS. UNIT TESTS CURRENTLY BUILD IN SINGLE FILE MODE,
// FOLLOWING <reference> TAGS. THESE EXPECT THIS FILE TO BE IN THE SOURCE TREE IN THE COMMON
// DIRECTORY, WHEREAS IN REALITY IT'S ONLY IN THE COMMON DIRECTORY AFTER BUILDING.

var isDebugBuild = true;